### ISSUE TITLE
fail to start 

### ISSUE THREAD

**Issue by Thunderbird2086** [rakusan2/Toastmasters-Timer-Overlay#16]
The latest commit failed to start while spatting errors blow
```
$ npm start 

> timer-overlay@1.2.3 start
> node server/js/index.js

/home/allen/workspace/toasmasters/Toastmasters-Timer-Overlay/server/js/index.js:267
                const status = socket.statusCode ?? 0;
                                                  ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/allen/workspace/toasmasters/Toastmasters-Timer-Overlay
npm ERR! command failed
npm ERR! command sh -c node server/js/index.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/allen/.npm/_logs/2021-12-22T14_44_51_769Z-debug.log
```

Environment 
```
$ uname -a
Linux debian10-64 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
$ npm --version 
7.5.2
```

Please advise

**Comment by Thunderbird2086** [comment]
Figured out what was wrong.  The latest nodejs solved the issue.
